### PR TITLE
IRV now handles missing values, and psychsyn handles NA results better

### PR DESCRIPTION
**Pull request by franciscowilhelm**
In response to  #16 and #14 , IRV now handles missing values, and psychsyn, when returning NA on its first try, tries to return non-NA results by resampling the item values matrix.

### CODE REVIEW

**Comment by ryentes** [comment]
So the users original ask was that the tibble 

```
df<-tribble(
+     ~A,~B,~C,
+     1,2,3,
+     1,NA,3)
```
would return  1, NA 

The proposed change would return
```
> irv(df)
[1] 1.000000 1.414214
```

I have to go through the function more carefully to form a strong perspective. But perhaps you could comment on which method is preferred and why. The only thing I can say at the moment is that I feel strongly that we should always return a vector or dataframe of length m for any m x n input.

**Comment by franciscowilhelm** [comment]
> So the users original ask was that the tibble
> 
> ```
> df<-tribble(
> +     ~A,~B,~C,
> +     1,2,3,
> +     1,NA,3)
> ```
> 
> would return 1, NA
> 
> The proposed change would return
> 
> ```
> > irv(df)
> [1] 1.000000 1.414214
> ```
> 
> I have to go through the function more carefully to form a strong perspective. But perhaps you could comment on which method is preferred and why. The only thing I can say at the moment is that I feel strongly that we should always return a vector or dataframe of length m for any m x n input.

Mhm... Computing the IRV for a person with missing data can be problematic (depending on the structure of missing data) and shifts the burden to the user – much like when calculating correlation coefficients with missing data andsoon.
Probably best practice would be to add the "na.rm" option in the arguments of the function, making users aware of the issue and giving them options. na.rm = FALSE would equal to what user was requesting, na.rm = TRUE to how it is now (always try to calculate irv for every case).
I'm not sure about the default though.

**Comment by ryentes** [comment]
Ok. If i'm understanding correctly, then in both na.rm=TRUE and na.rm=FALSE the function will return a vector of length M. In the first case it will attempt to return a value even if there are missing values, and return NA if it fails. If na.rm=FALSE then obs with missing data will return NA if that's true then I'm good to go.

**Comment by franciscowilhelm** [comment]
Yes, you're correct.

Example:
> irv(df, na.rm = FALSE)
[1]  1 NA
> irv(df, na.rm = TRUE)
[1] 1.000000 1.414214

**Pull request merged**
